### ISSUE TITLE
Doubled aluminium piece exnihilocreatio-1.12-0.3.2

### ISSUE THREAD

**Issue by LjeDamos** [BloodWorkXGaming/ExNihiloCreatio#120]
it is just doubled with different id numbers

![bandicam 2018-09-22 21-43-20-429](https://user-images.githubusercontent.com/20936024/45920670-9352d180-beb0-11e8-824d-a3f5dc7e8bfb.jpg)

**Comment by Skillotic0703** [comment]
It's because there are mods that oredict aluminium/aluminum as aluminium and/or aluminum and to make sure ex nihilo is compatible with both types of aluminium/aluminum it registers both as different ores but you can fix it by removing one of the entries in the config files.

1) In the main config file of ex nihilo (ExNihiloCreatio.cfg), set B:enableJSONLoading to true
2) Restart Minecraft
3) In the config file OreRegistry.json remove one entry that corresponds to Aluminium or Aluminum suiting your needs
4) Restart Minecraft and you'll see that there aren't two aluminium pieces anymore!

**Comment by SirLyle** [comment]
The solution appears to be for America complete its cultural victory ... too bad there are Americans and non-Americans working on this project. I will try to add *something* to check for doubled alumini?um.

**Comment by SirLyle** [comment]
Actually found the issue really easily, it's because of the thermal compat that got added, ironically the non-American added the Americanized spelling.
