### ISSUE TITLE
'Inspirations' crooks

### ISSUE THREAD

**Issue by Josral** [BloodWorkXGaming/ExNihiloCreatio#130]
'Inspirations' crooks are not 100% effective at getting string from infested leaves in exnihilo 3.2.

**Comment by SirLyle** [comment]
Don't have time to fix it right now but it is due to [this line](https://github.com/BloodyMods/ExNihiloCreatio/blob/54b23ac2d8304780bbc2ec03b8c745b821f9f142/src/main/java/exnihilocreatio/blocks/BlockInfestingLeaves.java#L262) (and [this one](https://github.com/BloodyMods/ExNihiloCreatio/blob/54b23ac2d8304780bbc2ec03b8c745b821f9f142/src/main/java/exnihilocreatio/blocks/BlockInfestedLeaves.java#L92))not being updated to check toolclass instead of checking for instances of ICrook.
