### ISSUE TITLE
Infested Leaves Crucible Crash

### ISSUE THREAD

**Issue by ghost** [BloodWorkXGaming/ExNihiloCreatio#140]
MC 1.12.2
Forge: 2796
EX Nihilo Creatio: 1.12-0.3.2

I added Infested Leaves to the CrucibleRegistryWood.json file and when trying to right click the leaves into the crucible I get the following crash.

https://pastebin.com/YGdDKUVN

**Comment by SirLyle** [comment]
So the I think the reason is because infest*ing* use an animated renderer (to do the color fade), which doesn't have a model to pull the sprite from. It should work if you define the "color" override in the json file. I've added a null check to the rendering code so while it might not render anything, it shouldn't cause crashes.

**Comment by SirLyle** [comment]
Fix pushed to curse.

**Comment by ghost** [comment]
Thank you for safe guarding against this.
