### ISSUE TITLE
Unknown issue see crash report

### ISSUE THREAD

**Issue by AJM10565** [BloodWorkXGaming/ExNihiloCreatio#206]
See the link for details. Pop-ups are annoying.
[https://paste.dimdev.org/edogiwacar.mccrash](url)

**Comment by SirLyle** [comment]
You appear to have messed up your link, it doesn't lead to what the text says it does.

Could you please update your Ex Nihilo Creatio version; the one you are currently running is several months old and multiple crashes have been fixed in that time (including one for that particular section of code).

Please report if that fixes your issue.

**Comment by SirLyle** [comment]
Closing this as you haven't responded in nearly a month. If the issue persists on the latest version of creatio, reopen with a description of what you were doing which led to the crash.
