### ISSUE TITLE
[Suggestion] Configureable Efficiency Enchant Speeds

### ISSUE THREAD

**Issue by CritFlaw** [BloodWorkXGaming/ExNihiloCreatio#212]
Configureable efficiency multipliers on a pack-dev level. Similar to how you can change the way capacitors in ender io scale, it would be great to be able to set the scale at which efficiency levels scale with the various levels of efficiency, or set specific values for each level. Currently, an efficiency 5 sieve is not that much faster from one with no efficiency.

Scale-ability could work on a square or cubic basis, (the Ender IO capacitor configs are a good reference). Or an easier option is letting the user decide specific values for how quickly materials should be sieved.

**Comment by SirLyle** [comment]
An unenchanted mesh takes 10 clicks (+1 to insert), efficiency five takes 3 clicks (+1 to insert), seems fairly different to me (maximum enchant level is also already configurable).

Some of the magic constants could be moved out into the configs, but I'm not sure choosing between linear/quadratic/cubic is worthwhile since it is limited to the speed that the player can click at and there isn't much room for differentiation between 10 and 1.

**Comment by CritFlaw** [comment]
Yes but it would be very useful in an ex compression machine.

**Comment by SirLyle** [comment]
Ex Compressum's sieve efficiency is a completely separate calculation from Creatio's. It does a linear (1 + 0.25 * Efficiency Level) * Food Modifier * Configurable Base Speed per tick.

While Creatio's is currently: 10 + floor(5*efficiency level * (1 + 0.2 * haste level)) per click

I am making creatio's

    base progress + efficiency level * efficiency scaling factor * (1 + haste level * haste scaling factor) per click

Which should make a haste 2 + eff 5 take 1 click with my planned defaults

Planned number of clicks (excluding insertion)

| Eff\Haste | 0 | 1 | 2 |
| --: | --: | --: | --: |
| 0 | 10 | 10 | 10 |
| 1 | 7 | 5 | 4 |
| 2 | 5 | 3 | 2 |
| 3 | 4 | 3 | 2 |
| 4 | 4 | 2 | 2 |
| 5 | 3 | 2 | 1 |

**Comment by CritFlaw** [comment]
Ah, I thought they grabbed the efficiency from Ex Nihilo

**Comment by SirLyle** [comment]
They grab the enchantment level from the item stack, and creatio adds the enchantment. But the calculation of how much progress to make per operation is calculated independently. It wouldn't make sense to do it as one calculation because the auto sieve works at the tick rate (ideally 20 ticks per second) while the manual sieves works at the player click rate which I think is ~ 2 clicks / second if you hold down right click.

Creatio will even accept normal "efficiency" if you manage to get it on a mesh so you could have a "Sieve Efficiency V, Efficiency V" mesh for an effective Efficiency X (same with fortune and luck of the sea).

**Comment by Insane96** [comment]
> | Eff\Haste	| 0 | 1 | 2
> | - | - | - | - |
> | 0	| 10	| 10	| 10
> | 1	| 7	| 5	| 4
> | 2	| 5	| 3	| 2
> | 3	| 4	| 3	| 2
> | 4	| 4	| 2	| 2
> | 5	| 3	| 2	| 1

Wait shouldn't haste still decrease clicks even without efficiency?

**Comment by SirLyle** [comment]
Good point.

Modified equation and defaults:

| Eff\Haste | 0 | 1 | 2 |
| --: | --: | --: | --: |
| 0 | 10 | 5 | 4 |
| 1 | 7 | 4 | 3 |
| 2 | 5 | 3 | 2 |
| 3 | 4 | 2 | 2 |
| 4 | 4 | 2 | 2 |
| 5 | 3 | 2 | 1 |
