### ISSUE TITLE
Techguns ores aren't readed

### ISSUE THREAD

**Issue by SNikolaBogdanic** [BloodWorkXGaming/ExNihiloCreatio#237]
I installed techguns-1.12.2-2.0.1.2_1 and exnihilocreatio-1.12.2-0.4.4, but i have a problem: Techguns adds its own ores, just as Copper, tin, Uranium, etc. But this aren't readed by the Ex Nihilo 's library as that (or at least i think that is what is happening), causing that the sieve don't drop the ores, unless i install Thermal Foundation or another similar that help with this. Can you solve this issue of compatibility between Techguns and ExNihilo?

**Comment by SirLyle** [comment]
The issue appears to be that Techguns is registering the oredicts for its blocks during FMLInitializationEvent instead of during item registration; because the InitializationEvent comes after item registration Ex Nihilo has already had to create its ore pieces/chunks. The titanium ore is being seen/generated because he has an item version which is registered to the ore dict during item registration.

@pWn3d1337 would you be willing to move your [ore dict registration](https://github.com/pWn3d1337/Techguns2/blob/e37528bad29dea96b537c4e52040bc65a3308687/src/main/java/techguns/TGBlocks.java#L201) to [item registration](https://github.com/pWn3d1337/Techguns2/blob/e37528bad29dea96b537c4e52040bc65a3308687/src/main/java/techguns/TGBlocks.java#L132), similar to how you have your normal items are registered.

**Comment by SNikolaBogdanic** [comment]
So we (or at least i) must wait to:
-Titanium pieces/chunks from ExNihilo.
-Correct Oredict registering from Techguns, moving it from ore blocks to items (Or something similar).

I understand that, correct me if i'm wrong.

**Comment by SirLyle** [comment]
The best fix would be for techguns to move their ore's oredict registration earlier in the loading process (i.e. during BlockItem registration); otherwise Creatio is going to have to add individual compatibility support for every single mod which does late registration.

In the meantime you can manually add them through the JSON files. To add copper/tin/lead/uranium to the game you just need to add the following lines to the OreRegistry.json file and corresponding entries to the SieveRegistry.json file.

```json
  {
    "name": "copper",
    "color": "ff9933",
    "ingot": "techguns:itemshared:79"
  },
  {
    "name": "tin",
    "color": "e6fff2",
    "ingot": "techguns:itemshared:80"
  },
  {
    "name": "lead",
    "color": "330066",
    "ingot": "techguns:itemshared:82"
  },
  {
    "name": "uranium",
    "color": "4e5b43"
  }
```

**Comment by SNikolaBogdanic** [comment]
Thanks! I will do it for my little skyblock modpack!

**Comment by SNikolaBogdanic** [comment]
And a cheap way to add Titanium ore to the sieve register?

**Comment by SirLyle** [comment]
Closing as a more complete fix would depend on techguns making changes to their oredict registration.
