### ISSUE TITLE
[Suggestion] Replace enableJSONLoading with a ternary option

### ISSUE THREAD

**Issue by SirLyle** [BloodWorkXGaming/ExNihiloCreatio#30]
enableJSONLoading is nice for getting new updates, but makes having your own recipes a (theoretical) pain to maintain.

I suggest having 3 options for how to handle the JSON configs:

* Ignore—only uses the default recipes (current enableJSONLoading = false behavior)
* JSONonly—JSON completely replaces the defaults (current enableJSONLoading = true behavior)
* Both—Both the defaults and the JSON are loaded (JSON second). This lets someone define their own recipes, while still getting future updates.

**Comment by BloodWorkXGaming** [comment]
Well, I can see a few problems with that.
1. I would have to make empty jsons by default if that mode is one (not
that big of a problem.)
2. If the user still has the old files still, non empty files for whatever
reason with the default recipes in them, then it might conflict with the
already registered stuff, and I would have to check all recipes whether
they already are registered
3. I would break the config files once again, unless I do some string stuff
instead of enum, which would be the correct way to go about it.

**Comment by majijn** [comment]
how about enabling each Json file individually? or would that open a whole other can of worms?

**Comment by SirLyle** [comment]
Most use cases would be covered by craft/modtweaker support, which would be more flexible.
