### ISSUE TITLE
Code Error with latest commit/change

### ISSUE THREAD

**Issue by jmac460** [BloodWorkXGaming/ExNihiloCreatio#61]
![image](https://user-images.githubusercontent.com/34420502/36362880-f7026234-14fd-11e8-98df-5e983a3d980b.png)

I was noticing that you use + a lot and i knew it wasnt the best solution... unless you have a very specific reason to. Do you mind sharing with me your thoughts on it?

**Comment by BloodWorkXGaming** [comment]
Welp, didn't do a lot with gradle im the past, didn't know it was bad to
use those, never really ran into any issues.
Just thought it was good practice to keep the dependencies always updated
because if players update both and it breaks I can fix it easier in dev.

Anyways, thanks for telling me that, I will look into it.

jmac460 <notifications@github.com> schrieb am Mo., 19. Feb. 2018, 05:56:

**Comment by SirLyle** [comment]
Tried my hand at cleaning up the [gradle on a new branch](https://github.com/BloodWorkXGaming/ExNihiloCreatio/tree/Gradle) using a setup I've seen several other mods use of putting the dependency version numbers in a separate easier to maintain file.

**Comment by BloodWorkXGaming** [comment]
Well, I am pretty sure it doesn't matter and in my opinion it is actually
worse to use a fixed version.

Like do you want to check every maven every day just to see if there are
updates?

SirLyle <notifications@github.com> schrieb am Sa., 24. Feb. 2018, 04:14:

**Comment by BloodWorkXGaming** [comment]
I partly changed this now, not sure whether it actually is better tho ^^
