### ISSUE TITLE
Upgraded Mesh's should work with downgrades materials (uploaded by BloodWorkXGaming's Request)

### ISSUE THREAD

**Issue by TynotWolfDragon** [BloodWorkXGaming/ExNihiloCreatio#99]
![image](https://user-images.githubusercontent.com/16494408/42734105-30749236-880c-11e8-9ea1-684607e67a29.png)

**Comment by SirLyle** [comment]
Currently meshes only sieve what has recipes. Is this a request to have the default recipes include all blocks for all meshes or for meshes to include on lower tier meshes' recipes (with equal or greater chances)?

I'm not sure I'd support the second because some packs (e.g. Sky Factory 3 with the predecessor mod) used the separation to great effect. But if this is just a suggestion to mix up the default recipes it'd be an interesting to revamp the default progression.

Could you provide a little more detail for those of us not involved in the conversation referred to?

**Comment by TynotWolfDragon** [comment]
Perhaps a configuration option to enable that latter bit? Maybe even an option for the first bit too. For someone who just downloads his favorite mods on curse like myself, swapping meshes every 5 minutes to get what I need is quite annoying, and honestly uninteresting. All it adds, in my opinion, is busy work.

**Comment by SirLyle** [comment]
Option to flatten sieves tiers merged. Adding to curse soon.
